chrome:
	deno run --allow-net --allow-read=./ --allow-write=./ --unstable --no-check build.ts


firefox:
	deno run --allow-net --allow-read=./ --allow-write=./ --unstable --no-check build.ts --firefox
